- chart/templates/deployment.yaml
- chart/values.yaml
- Moves the default fallback from deployment files.
- Adds comments to the values file for better understanding what the values do.
> chore: Moves defaults to values file & adds comments.

- .github/workflows/release.yml
@moshloop please do have a look and give feedback thanks.
> chore: update release workflow to update incident-commander-chart

- api/v1/kubernetes.go
- api/v1/types.go
- fixtures/kubernetes.yaml
- scrapers/aws/aws.go
- scrapers/azure/devops/pipelines.go
- scrapers/common.go
- scrapers/file/file.go
- scrapers/kubernetes/kubernetes.go
- scrapers/sql/sql.go
After merging this PR, merge: https://github.com/flanksource/aws-sandbox/pull/94
> feat: support for kubernetes relationships

- scrapers/kubernetes/events.go
When the involved object's `uid` is not a valid UUID, we use `Kubernetes/{kind}/{namespace}/{name}` as the `uid`.
> fix: events of a node

- api/v1/common.go
- chart/crds/configs.flanksource.com_scrapeconfigs.yaml
- fixtures/expected/file-script-gotemplate.json
- fixtures/file-script-gotemplate.yaml
- scrapers/runscrapers_test.go
- added new fixture that showcases transformation using go template
> fix: json struct tag for go templates.

- api/v1/common.go
- api/v1/interface.go
- db/config.go
- db/models/config_item.go
- fixtures/data/test.yaml
- fixtures/file-local-creation-date.yaml
- scrapers/processors/json.go
Resolves https://github.com/flanksource/config-db/issues/134
> feat: support extracting creation and deletion date from config body

- chart/templates/deployment.yaml
- scrapers/runscrapers.go
> chore: add scraper id to job history and update chart

- api/v1/kubernetes.go
- chart/crds/configs.flanksource.com_scrapeconfigs.yaml
- fixtures/github-actions.yaml.old
- fixtures/kubernetes_file.yaml
- scrapers/kubernetes/kubernetes_file.go
* Updated CRD and fixture
Due to this there was a conflict in the generated CRD and the YAML parser.
> fix: struct tag in Kubernetes file config struct

- chart/templates/deployment.yaml
- chart/values.yaml
- cmd/root.go
- cmd/server.go
- jobs/cleanup.go
- jobs/jobs.go
Fixes: https://github.com/flanksource/canary-checker/issues/808
> feat: add retention period for changes and analysis

- api/v1/interface.go
- go.mod
- go.sum
- scrapers/changes/rules.go
- scrapers/changes/rules.yaml
- scrapers/changes/rules_test.go
- scrapers/changes/template_utils.go
- scrapers/runscrapers.go
Resolves: https://github.com/flanksource/config-db/issues/251
> feat: change type & summary rules

- api/v1/interface.go
- db/config.go
- db/models/config_item.go
- go.mod
- go.sum
- hack/generate-schemas/go.mod
- hack/generate-schemas/go.sum
- scrapers/aws/aws.go
- scrapers/kubernetes/kubernetes.go
Waiting for: https://github.com/flanksource/duty/pull/177
> feat: Save config status for Node,Pod and EC2 instance

- fixtures/kubernetes.yaml
- scrapers/kubernetes/kubernetes.go
Fixes: https://mission-control.azure.lab.flanksource.com/incidents/0188b498-865c-e51b-848e-56e508557681 & https://mission-control.azure.lab.flanksource.com/incidents/0188b497-f9c5-466a-a820-bebc3620fae0
> chore: remove generation and uptime from kubernetes status

- chart/templates/_helpers.tpl
- chart/templates/deployment.yaml
- chart/templates/serviceaccount.yaml
- chart/values.yaml
- allows override to point to existing SA
- allows annotation injection when creating S
- cleaned up some nindent vs indent discrepencies
> feat: allow serviceAccount annotation configuration

- api/v1/interface.go
- db/config.go
- go.mod
- go.sum
- scrapers/kubernetes/kubernetes.go
> feat: add health status for kubernetes objects

- db/update.go
- scrapers/runscrapers.go
Resolves: https://github.com/flanksource/config-db/issues/289
> fix: config change summary from patch

- fixtures/expected/file-git.json
- scrapers/kubernetes/events.go
Resolves: https://github.com/flanksource/config-db/issues/293
> fix: remove `manageFields` from Kubernetes event

- db/config.go
- db/models/config_item.go
- db/update.go
- scrapers/kubernetes/kubernetes.go
Fixes: https://github.com/flanksource/config-db/issues/284
> fix: mark evicted pods as deleted

- scrapers/azure/azure.go
- scrapers/azure/azure_test.go
resolves: https://github.com/flanksource/config-db/issues/318
> feat: establish azure resource relationship to resource group & subscription

- chart/templates/serviceaccount.yaml
- chart/values.yaml
resolves: https://github.com/flanksource/config-db/issues/339
https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/
> feat: rbac on helm

- scrapers/kubernetes/kubernetes.go
- scrapers/runscrapers_test.go
resolves: https://github.com/flanksource/config-db/issues/341
> feat: link kubernetes resources to their namespace

- scrapers/kubernetes/kubernetes.go
resolves: https://github.com/flanksource/config-db/issues/359
> feat: add apiVersion tag to kubernetes config items

- api/v1/aws.go
- scrapers/aws/aws.go
- scrapers/aws/trusted_advisor.go
resolves: https://github.com/flanksource/config-db/issues/360
> feat: aws resource linking

- api/v1/kubernetes.go
- db/config.go
- db/update.go
- scrapers/changes/rules.yaml
- scrapers/kubernetes/events_watch.go
- scrapers/kubernetes/kubernetes.go
- scrapers/run.go
- scrapers/runscrapers.go
resolves: https://github.com/flanksource/config-db/issues/379
> fix: handle deleted pods from watch events

- go.mod
- go.sum
- jobs/cleanup.go
- jobs/jobs.go
- jobs/jobs_test.go
- jobs/retention.go
- jobs/suite_test.go
resolves: https://github.com/flanksource/config-db/issues/382
> feat: improve config cleanup job

- db/update.go
resolves: https://github.com/flanksource/config-db/issues/393
> fix: save changes for events that match a change rule

- scrapers/run.go
resolves: https://github.com/flanksource/config-db/issues/402
> fix: undeleting items

- jobs/cleanup.go
resolves: https://github.com/flanksource/config-db/issues/401
> fix: config cleanup job

- jobs/retention.go
resolves: https://github.com/flanksource/config-db/issues/400
> fix: continue processing change rules on error

- controllers/scrapeconfig_controller.go
- fixtures/kubernetes.yaml
- scrapers/cron.go
resolves: https://github.com/flanksource/config-db/issues/414
> fix: parallel scraping in operator mode

- fixtures/kubernetes.yaml
- scrapers/kubernetes/kubernetes.go
> chore: update k8s config relation lookup

- db/models/config_change.go
- db/update.go
resolves: https://github.com/flanksource/config-db/issues/444
> fix: zero value created_at in config changes

- fixtures/aws.yaml
comiting this only to create a new release.
the last hot fix commit wasn't released.
> fix: fixture

- go.mod
- go.sum
- hack/generate-schemas/go.mod
- hack/generate-schemas/go.sum
- jobs/cleanup.go
- jobs/sync_upstream.go
- scrapers/cron.go
merge after: https://github.com/flanksource/duty/pull/665
> feat: job history cleanup

- cmd/root.go
- go.mod
- go.sum
- scrapers/kubernetes/kubernetes.go
* setup ketall logging
* update ketall that fixes deadlock on support for custom kube config
resolves: https://github.com/flanksource/mission-control-registry/issues/111
depends on: https://github.com/flanksource/ketall/pull/8
> fix: ketall

- db/config_scraper.go
resolves: https://github.com/flanksource/config-db/issues/495
> fix: don't start scraper job from the reconciler on startup

- scrapers/kubernetes/kubernetes.go
use the existing kube client by GroupVersionKind instead of ketall to fetch resources individually.
`ketall.KetOne` is unoptimized for high volume calls and introduces massive throttling.
> fix: incremental scraper

- api/v1/types.go
- db/update.go
> fix: diff not being generated due to missing id

- cmd/operator.go
- cmd/root.go
- cmd/server.go
- go.mod
- go.sum
- hack/generate-schemas/go.mod
- hack/generate-schemas/go.sum
resolves:  https://github.com/flanksource/config-db/issues/529
depends on: https://github.com/flanksource/duty/pull/749
> feat: check if migrations have run on startup

- scrapers/azure/azure.go
resolves: https://github.com/flanksource/config-db/issues/528
> feat: azure resources console link

- scrapers/aws/aws.go
resolves: https://github.com/flanksource/config-db/issues/527
> feat: links to AWS resources

- go.mod
- go.sum
- hack/generate-schemas/go.mod
- hack/generate-schemas/go.sum
- scrapers/processors/json.go
The log line helps to find out which config is causing this error https://github.com/flanksource/mission-control-registry/issues/147
> fix: log config_id on relationship failure. bump duty

- go.mod
- go.sum
- hack/generate-schemas/go.mod
- hack/generate-schemas/go.sum
- scrapers/aws/aws.go
- scrapers/runscrapers_test.go
merge after: https://github.com/flanksource/duty/pull/788
The errors occured during session creation were ignored.
> fix: handle session creation errors

- scrapers/cron.go
- scrapers/run_now.go
resolves: https://github.com/flanksource/config-db/issues/578
> fix: log run now scrapes to job history

- scrapers/kubernetes/kubernetes.go
resolves: https://github.com/flanksource/config-db/issues/601
> feat(kubernetes): use different prefix for crossplane objects

- api/v1/kubernetes.go
- db/update.go
resolves: https://github.com/flanksource/config-db/issues/610
> feat: watch nodes by default

- scrapers/aws/aws.go
Fixes: https://github.com/flanksource/config-db/issues/604
> chore: sort services in assumeRolePolicyDoc

- scrapers/cron.go
resolves: https://github.com/flanksource/config-db/issues/617
> fix: dangling scrapers jobs

- db/update.go
- go.mod
- go.sum
- hack/generate-schemas/go.mod
- hack/generate-schemas/go.sum
resolves: https://github.com/flanksource/is-healthy/issues/34
> feat: change severity

- scrapers/aws/aws.go
- scrapers/kubernetes/kubernetes.go
Fixes: https://github.com/flanksource/config-db/issues/618
> chore: exclude labels

- scrapers/kubernetes/events.go
- scrapers/kubernetes/kubernetes.go
- scrapers/runscrapers.go
resolves: https://github.com/flanksource/config-db/issues/639
> feat: custom annotations

- db/update.go
- scrapers/aws/cloudtrail.go
resolves: https://github.com/flanksource/config-db/issues/652
> feat: count orphaned changes as error

- jobs/cleanup.go
> fix: break loop in cleanup

- .gitignore
- api/v1/interface.go
- api/v1/interface_test.go
- cmd/run.go
- db/update.go
- go.mod
- go.sum
- hack/generate-schemas/go.mod
- hack/generate-schemas/go.sum
- scrapers/cron.go
- scrapers/run.go
- scrapers/runscrapers_test.go
resolves: https://github.com/flanksource/config-db/issues/656
> feat: scrape summary

- api/v1/aws.go
- scrapers/aws/aws.go
* map creation/deletion timestamps
* map health & status
resolves: https://github.com/flanksource/config-db/issues/699
> feat(ecs task definition): fetch inactive & deleting definitions

- db/models/config_change.go
Fixes: https://github.com/flanksource/config-db/issues/658
> fix: change summary should be empty string instead of null

- scrapers/aws/aws.go
> chore: fix load balancer relationship direction

- Makefile
- api/cache.go
- api/context.go
- api/v1/types.go
- db/update.go
- scrapers/kubernetes/informers.go
- scrapers/kubernetes/kubernetes.go
resolves: https://github.com/flanksource/config-db/issues/708
> feat: scraper scoped lookup by external ids

- api/v1/interface.go
- db/config.go
- db/update.go
- fixtures/aws.yaml
- scrapers/aws/aws.go
resolves: https://github.com/flanksource/config-db/issues/728
> feat(aws): region, zone & zone id are not account specific

- scrapers/kubernetes/kubernetes.go
resolves: https://github.com/flanksource/config-db/issues/704
> feat: link pods to services via endpoints

- api/v1/kubernetes.go
- db/update.go
- scrapers/kubernetes/kubernetes.go
resolves: https://github.com/flanksource/config-db/issues/726
> fix: kubernetes diff exclusion via annotation

- api/v1/interface.go
- db/config.go
- db/models/config_item.go
- db/update.go
- scrapers/kubernetes/kubernetes.go
> feat: set argo resources as children

- api/v1/common.go
- api/v1/interface.go
- chart/crds/configs.flanksource.com_scrapeconfigs.yaml
- config/schemas/config_aws.schema.json
- config/schemas/config_azure.schema.json
- config/schemas/config_azuredevops.schema.json
- config/schemas/config_file.schema.json
- config/schemas/config_githubactions.schema.json
- config/schemas/config_kubernetes.schema.json
- config/schemas/config_kubernetesfile.schema.json
- config/schemas/config_sql.schema.json
- config/schemas/config_trivy.schema.json
- config/schemas/scrape_config.schema.json
- go.mod
- hack/generate-schemas/go.mod
- scrapers/processors/json.go
- scrapers/processors/script.go
* set health, status & readiness if empty
> feat: run relationships selector and properties after transformation

- db/update.go
- scrapers/aws/cloudtrail.go
resolves: https://github.com/flanksource/config-db/issues/814
```yaml
scrape_summary:
AWS::::Account:
unchanged: 1
AWS::AvailabilityZone:
unchanged: 12
AWS::AvailabilityZoneID:
unchanged: 12
AWS::CloudFormation::Stack:
updated: 21
AWS::EBS::Volume:
unchanged: 10
AWS::EC2::DHCPOptions:
unchanged: 3
AWS::EC2::Instance:
unchanged: 3
change:
orphaned:
AttachNetworkInterface: 1095
AWS::EC2::NetworkInterface:
change:
orphaned:
AttachNetworkInterface: 1095
CreateNetworkInterface: 1101
DeleteNetworkInterface: 3646
ModifyNetworkInterfaceAttribute: 1095
AWS::EC2::NetworkInterfaceAttachment:
change:
orphaned:
AttachNetworkInterface: 1095
DetachNetworkInterface: 1095
ModifyNetworkInterfaceAttribute: 1095
AWS::EC2::RouteTable:
updated: 2
unchanged: 4
AWS::EC2::SecurityGroup:
unchanged: 10
change: …
```
> fix: report cloudtrail events with no resource

- scrapers/terraform/mask.go
- scrapers/terraform/mask_test.go
- scrapers/terraform/models.go
- scrapers/terraform/path.go
- scrapers/terraform/terraform.go
- scrapers/terraform/testdata/cloudflare.tfstate
- scrapers/terraform/testdata/cloudflare.tfstate.expected
resolves: https://github.com/flanksource/config-db/issues/834
> feat: terraform mask sensitive attributes

- api/v1/scrapeconfig_types.go
- cmd/root.go
- go.mod
- go.sum
- hack/generate-schemas/go.mod
- hack/generate-schemas/go.sum
- scrapers/cron.go
resolves: https://github.com/flanksource/config-db/issues/840
merge after: https://github.com/flanksource/duty/pull/968
> feat: scraper concurrency

- db/update.go
Fixes: https://github.com/flanksource/config-db/issues/884
> fix: use external id or id if name does not exist

- db/update.go
- hack/generate-schemas/main.go
resolves: https://github.com/flanksource/duty/issues/740
> feat: save health updates as config changes

- scrapers/aws/aws.go
Fixes: https://github.com/flanksource/config-db/issues/891
> fix: sorting for IAM Role, IAM Profile & EC2 RouteTables

- db/update.go
resolves: https://github.com/flanksource/config-db/issues/914
> fix: config_items_pkey constraint error

- scrapers/kubernetes/informers.go
resolves: https://github.com/flanksource/config-db/issues/978
Doesn't support CRDs though.
Seems to be on a TODO
https://github.com/kubernetes/client-go/blob/v0.28.2/informers/generic.go#L98
> feat: support shared informer for any GVK

- db/update.go
- fixtures/expected/file-git.json
- scrapers/changes/rules.go
- scrapers/changes/rules_test.go
resolves: https://github.com/flanksource/config-db/issues/974
> feat: show change mapping transormation errors in scraper job history

- jobs/cleanup.go
Fixes: https://github.com/flanksource/config-db/issues/1029
> chore: set config analysis status to closed for old non observed ones

- changes/fingerprint.go
- changes/fingerprint_test.go
- changes/testdata/helm_upgrade_failed.json
- changes/testdata/helm_upgrade_failed_2.json
this matches kubernetes event names
resolves: https://github.com/flanksource/config-db/issues/1044
> feat: detect 16char long hex strings

- db/changes.go
Fixes: https://github.com/flanksource/config-db/issues/1052
> chore: update fingerprint query to use index

- scrapers/kubernetes/hook_aws.go
- scrapers/kubernetes/kubernetes.go
resolves: https://github.com/flanksource/config-db/issues/1079
> fix: kubernetes node pod relationship

- scrapers/kubernetes/events_watch.go
- scrapers/kubernetes/informers.go
Shared informers were inconsistently cached.
The hostname from the rest config was used as the cache id when creating a shared informer.
However, when removing it, an empty string was used.
> fix: shared informer cache id

- api/v1/common.go
- api/v1/interface.go
- api/v1/types.go
- db/config.go
- scrapers/aws/aws.go
- scrapers/kubernetes/kubernetes.go
> fix: config external lookup references for aws

- api/context.go
Fixes: https://github.com/flanksource/config-db/issues/1062
> chore: make consume events/resources use temp cache

- changes/fingerprint.go
Fixes: https://github.com/flanksource/config-db/issues/1113
> chore: add change type to tokenizer

- scrapers/cron.go
- scrapers/kubernetes/events_watch.go
related: https://github.com/flanksource/config-db/issues/1121
> fix: improve event watcher error handling

- db/update.go
resolves: https://github.com/flanksource/config-db/issues/1125
> use status & description in health changes

- db/update.go
- scrapers/aws/trusted_advisor.go
resolves: https://github.com/flanksource/config-db/issues/1124
> chore: increase slow diff threshold to 1s from 500ms

- scrapers/kubernetes/kubernetes.go
resolves: https://github.com/flanksource/config-db/issues/1015
> feat: sort .status.conditions

- scrapers/kubernetes/hook_flux.go
Fixes: https://github.com/flanksource/config-db/issues/1130
> feat: kustomization objects should not have kustomization parents

- db/config_scraper.go
depends on : https://github.com/flanksource/duty/pull/1182
> feat: save namespace of config scrapers

- scrapers/cron.go
resolves: https://github.com/flanksource/config-db/issues/1160
> fix: log scraper job schedule error to its own history

- scrapers/changes/rules.yaml
- scrapers/changes/rules_test.go
resolves: https://github.com/flanksource/config-db/issues/1176
> fix: remove incorrect change mappings

- api/v1/interface.go
- db/update.go
Fixes: https://github.com/flanksource/config-db/issues/1180
This PR needs to be merged first: https://github.com/flanksource/duty/pull/1205
> chore: add lag in summary

- api/cache.go
- api/context.go
- db/update.go
Fixes: https://github.com/flanksource/config-db/issues/1193
> fix: handle scraper less type cache hits

- cmd/run.go
> fix: removed unused flag

- scrapers/incremental.go
- scrapers/kubernetes/kubernetes.go
- scrapers/run_test.go
resolves: https://github.com/flanksource/config-db/issues/1211
> fix: scrape metrics improvements

- scrapers/kubernetes/informers.go
- scrapers/kubernetes/informers_test.go
resolves: https://github.com/flanksource/config-db/issues/1247
> feat: support comparator for the same object

- api/cache.go
- scrapers/incremental.go
```
For events of temporary kubernetes resources (like a pod created by a canary and immediately deleted),
it's possible that the involved object is deleted by the time we query it.
If we don't find the involved object we re-queue the event.
The involved object is never found and the re-queuing happens indefinitely.
This resulted in ever increasing queue and high db calls.
* fix: mark the scrape context as incremental
* fix: change labels on temp cache metrics
```
resolves: https://github.com/flanksource/config-db/issues/1288
> fix: prevent infinite re-queuing of events with missing involved objects

- api/cache.go
this happens when a incremental scrape runs along with a full scrape
resolves: https://github.com/flanksource/config-db/issues/1300
> fix: handle concurrent access on tempcache

- api/v1/interface.go
- db/config.go
- scrapers/changes/extraction_test.go
- scrapers/changes/rules_test.go
- scrapers/processors/json.go
ScrapeReult.AsMap does not need json Marshaling and Unmarshaling
> chore: avoid json serialization in scrape result map

- utils/kube/fetcher.go
> chore: move k8s client creation out of for loop

- scrapers/run_now.go
resolves: https://github.com/flanksource/config-db/issues/866
> fix: run now with no jitter wait

- scrapers/cron.go
related: https://github.com/flanksource/config-db/issues/1384
> fix(scrapeconfig): clear stale error statuses after successful run

- api/v1/kubernetes.go
- scrapers/cron.go
- scrapers/kubernetes/informers.go
Depends on https://github.com/flanksource/duty/pull/1355
> chore: use host as cache key for informers

- scrapers/kubernetes/informers.go
was accidentally removed here: https://github.com/flanksource/config-db/pull/1419/files#diff-50dd5d30ead402490cfb80d588355de7f86f706f3ff54b419f551a662846db18L387-L390
> feat: Set kind & apiVersion on objects from informer

- scrapers/aws/trusted_advisor.go
- scrapers/common.go
- scrapers/run.go
resolves: https://github.com/flanksource/config-db/issues/1436
> feat: trusted advisor check min interval

- db/config.go
Fixes: https://github.com/flanksource/config-db/issues/1449
> fix: handle sharelock deadlock error

- scrapers/kubernetes/ketall.go
Fixes: https://github.com/flanksource/config-db/issues/1462
Depends on: https://github.com/flanksource/duty/pull/1404
> fix: handle new crd creation leading to deletion of all resources

- scrapers/azure/active_directory.go
resolves: https://github.com/flanksource/config-db/issues/1463
dependsOn: https://github.com/flanksource/is-healthy/pull/176
> feat: pull app registration credentials

- api/v1/gcp.go
- api/v1/gcp_test.go
- chart/crds/configs.flanksource.com_scrapeconfigs.yaml
- config/schemas/config_gcp.schema.json
- config/schemas/scrape_config.schema.json
- scrapers/gcp/gcp.go
Distinguish feature flags and the asset type passed to assetlist API.
resolves: https://github.com/flanksource/config-db/issues/1534
> fix: GCP feature flags (in includes)

- jobs/cleanup.go
> fix: success count for config cleanup job

- api/v1/gcp.go
- api/v1/interface.go
- db/update.go
- scrapers/gcp/cloudsql_backup.go
- scrapers/gcp/gcp.go
- scrapers/gcp/iam.go
- scrapers/gcp/structpb_utils.go
- scrapers/gcp/types.go
Fixes: https://github.com/flanksource/config-db/issues/1598
> chore(gcp): use fetched results for sql backups, update parent relationships

- scrapers/kubernetes/hook_flux.go
- scrapers/kubernetes/hooks.go
- scrapers/kubernetes/kubernetes.go
Fixes: https://github.com/flanksource/config-db/issues/935
> chore: add git source as a property in flux
