.github/workflows/lint.yml
scrapers/aws/aws.go

Needed to set the MaxResults 50 since we are getting the following error:
```
api error ValidationException: 1 validation error detected: Value '100' at 'maxResults' failed to satisfy constraint: Member must have value less than or equal to 50
```

fix: set max results to 50 in SSM describeInstancesPatches

---

README.md

This PR resolves a few issues in the README file for `config-db` to primarily improve clarity and readability for new contributors/users and ensure that the setup commands work "out of the box".

chore(docs): improve the clarity of the README and fix the run commands in setup

---

scrapers/sql/sql.go

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6f1a494]
goroutine 68 [running]:
github.com/flanksource/config-db/scrapers/sql.SqlScraper.Scrape({}, _, {{0xc0003acc30, 0x24}, {0x0, 0x0}, {0xc000b71038, 0x3}, {0x0, 0x0, ...}, ...})
/app/scrapers/sql/sql.go:33 +0x1b4
github.com/flanksource/config-db/scrapers.Run(0xc00094d2c0, {0xc0024a75b0, 0x1, 0x0?})
/app/scrapers/runscrapers.go:42 +0x551
github.com/flanksource/config-db/scrapers.RunScraper({{0xc0003acc30, 0x24}, {0x0, 0x0}, {0xc000b71038, 0x3}, {0x0, 0x0, 0x0}, {0x0, ...}, ...})
/app/scrapers/run.go:21 +0x2e8
github.com/flanksource/config-db/cmd.startScraperCron.func2()
/app/cmd/server.go:92 +0x58 …
```

fix: nil pointer error in sql scraper

---

api/v1/trivy.go
fixtures/trivy.yaml

The default scan timeout on Trivy is 5m which appears to be pretty low for large clusters.
It's failing to scan on our cluster for instance
`k8s scan error: context deadline exceeded`
https://github.com/aquasecurity/trivy/issues/2169#issuecomment-1134766285

feat: added timeout flag to Trivy scraper

---

cmd/server.go
db/config_scraper.go

Prevent the same config being scraped twice

fix: remove running the same job twice

---

api/v1/interface.go
db/update.go
scrapers/trivy/models.go
scrapers/trivy/trivy.go

Resolves: https://github.com/flanksource/config-db/issues/238
* Grouping by pkg name. Reduced from ~470 analysis reports to just ~90 reports
* Store misconfigurations as well in addition to vulnerabilities.

feat: group trivy analysis by package names

---

api/v1/interface.go
db/models/config_change.go
db/people.go
db/update.go
scrapers/aws/aws.go
scrapers/aws/cloudtrail.go

Resolves: https://github.com/flanksource/config-db/issues/216
Didn't find any events that actually mapped to a user.
```
select distinct external_created_by from config_changes
+------------------------------------------------------------------+
| external_created_by                                              |
|------------------------------------------------------------------|
| AWSServiceRoleForAmazonEKS                                       |
| eksctl-flanksource-canary-cluster-clus-ServiceRole-1UJQ53DFHT859 |
| spotinst-iam-stack-d5xzp-SpotinstRole-117P4HAZYZJD0              |
| eksctl-flanksource-canary-cluster-NodeInstanceRole-79QOSKKDW3PB  |
+------------------------------------------------------------------+
```

feat: map cloudtrail events' username to a person

---

api/v1/interface.go

In this case, config was in string type not struct, which made json.Marshal and Unmarshal error
```
2023-06-16T08:41:43.347+0530	ERROR	failed to unmarshal config: json: cannot unmarshal string into Go value of type map[string]interface {}
2023-06-16T08:41:43.347+0530	ERROR	failed to unmarshal config: json: cannot unmarshal string into Go value of type map[string]interface {}
2023-06-16T08:41:43.347+0530	ERROR	failed to unmarshal config: json: cannot unmarshal string into Go value of type map[string]interface {}
2023-06-16T08:41:43.347+0530	ERROR	failed to unmarshal config: json: cannot unmarshal string into Go value of type map[string]interface {}
2023-06-16T08:41:43.347+0530	ERROR	failed to unmarshal config: json: cannot unmarshal string into Go value of type map[string]interface {} …
```

fix: handle already json marshaled string in AsMap

---

scrapers/kubernetes/kubernetes.go

Fix errors like these:
```
2023-06-16T08:32:48.465+0530	ERROR	Error scraping : failed to extract attributes: no id defined for: ComponentStatus/etcd-0 (): id= name= type= transform= exclude=[{$.status.lastCheck} {$.status.lastTransitionedTime} {$.status.checkStatus.*.lastTransitionedTime}]
2023-06-16T08:32:48.466+0530	ERROR	Error scraping : failed to extract attributes: no id defined for: ComponentStatus/controller-manager (): id= name= type= transform= exclude=[{$.status.lastCheck} {$.status.lastTransitionedTime} {$.status.checkStatus.*.lastTransitionedTime}]
2023-06-16T08:32:48.466+0530	ERROR	Error scraping : failed to extract attributes: no id defined for: ComponentStatus/scheduler (): id= name= type= transform= exclude=[{$.status.lastCheck} {$.status.lastTransitionedTime} …
```

fix: generate id for kubernetes components which dont have one

---

chart/templates/_helpers.tpl

Chart upgradation failing
```
Helm upgrade failed: error while running post render on files: no matches for Id ServiceAccount.v1.[noGrp]/config-db-sa.[noNs]; failed to find unique target for patch ServiceAccount.v1.[noGrp]/config-db-sa.[noNs]
```

fix: add -sa suffix in default service account name

---

db/config.go
fixtures/expected/file-git.json

Right now, namespace for all kubernetes objects is empty

fix: copy namespace from scrape result to config item

---

db/update.go
scrapers/kubernetes/kubernetes.go

resolves: https://github.com/flanksource/config-db/issues/306

feat: generate config relationships from kubernetes ownerRef

---

.dockerignore
Makefile
build/Dockerfile
chart/Chart.yaml
chart/templates/deployment.yaml
chart/templates/postgres.yaml
chart/values.yaml
cmd/operator.go
cmd/run.go
cmd/server.go
db/init.go
main.go
scrapers/runscrapers_suite_test.go

resolves: https://github.com/flanksource/config-db/issues/305

feat: embedded db

---

api/v1/interface.go
db/config.go
db/update.go
scrapers/azure/azure.go

resolves: https://github.com/flanksource/config-db/issues/332

feat: derived config id

---

scrapers/kubernetes/kubernetes.go
scrapers/kubernetes/kubernetes_test.go

resolves: https://github.com/flanksource/config-db/issues/347

feat: Kubernetes Linking

---

scrapers/runscrapers.go

```
Error scraping : operation error CloudTrail: LookupEvents, exceeded maximum number of attempts, 3, https response error StatusCode: 400, RequestID: 7d6808be-63c3-4b2c-904b-a8ac539007bf, api error ThrottlingException: Rate exceeded
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x32cdfec]
goroutine 108 [running]:
github.com/flanksource/duty/models.(*JobHistory).AddError(0xc000d5b450, {0xc004448540, 0xd5})
/go/pkg/mod/github.com/flanksource/duty@v1.0.321/models/job_history.go:101 +0xec
github.com/flanksource/config-db/scrapers.Run({0x8d9f890, 0xc000d23310})
/app/scrapers/runscrapers.go:91 +0xa6d
github.com/flanksource/config-db/scrapers.RunScraper({0x8d9f890, 0xc000d23310})
/app/scrapers/run.go:12 …
```

fix: nil pointer panic on error logging for job history ctx

---

db/config.go
scrapers/azure/azure.go
scrapers/kubernetes/kubernetes.go

Azure VMs that run kubernetes nodes are part of a different API that we were never scraping before

feat: scrape azure scale set vms and link to k8s

---

scrapers/run.go

`ConsumeKubernetesWatchEvents` job, which runs `@every 15s`, was making queries to
- deleting configs
- reviving deleted configs
merge after: https://github.com/flanksource/duty/pull/548

fix: management of stale config items

---

scrapers/kubernetes/kubernetes.go

@dabasvibhor Was facing this error in BCB
```log
2024-03-05T09:45:10.547    DEBUG    excluding event object    {"name": "pg-test-app", "namespace": "mission-control", "reason": "Created"}
panic: interface conversion: interface {} is nil, not string
goroutine 89 [running]:
github.com/flanksource/config-db/scrapers/kubernetes.extractResults({{{0x8f1ccf8, 0xc00ea3f5c0}, {0x8f51c20, 0xc0008ac630}, 0x0, 0x0, 0x85aeac8, 0x85aead0, {0x8effbd8, 0xc000451
740}}}, ...)
/app/scrapers/kubernetes/kubernetes.go:337 +0x4c14
github.com/flanksource/config-db/scrapers/kubernetes.KubernetesScraper.Scrape({}, {0x8f554d0, 0xc00023f9f0})
/app/scrapers/kubernetes/kubernetes.go:93 +0x315
github.com/flanksource/config-db/scrapers.Run({0x8f554d0, 0xc00023f9f0})
/app/scrapers/runscrapers.go:44 +0x35d …
```

chore: handle nil conversion in k8s scraper

---

fixtures/kubernetes.yaml

```
Error from server (BadRequest): error when creating "fixtures/kubernetes.yaml": ScrapeConfig in version "v1" cannot be handled as a ScrapeConfig: strict decoding error: unknown field "spec.kubernetes[0].exclusions.label"
```

chore: update labels key in kubernetes fixture

---

db/config.go
db/models/config_item.go
db/update.go

resolves: https://github.com/flanksource/config-db/issues/476
We were generating deterministic hash for an empty string.

fix: deterministic id

---

scrapers/kubernetes/events_watch.go
scrapers/kubernetes/kubernetes.go
scrapers/processors/json.go

resolves: https://github.com/flanksource/config-db/issues/480
configs were incorrectly tagged because watch kubernetes event job wasn't using the custom kubeconfig at all. So it would always watch events on the default kubeconfig cluster and then tag the scraped configs with a different cluster.

fix: incorrect tags 

---

db/config_scraper.go
go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum
scrapers/cron.go

* don't run deleted scrapers
The cron job for `consumeKubernetesWatchEvents` was not being cleared before another one of it was run. With 5 spec update, we would have had 5 of those jobs running. 
merge after: https://github.com/flanksource/duty/pull/670

fix: duplicate watch jobs for kubernetes scraper

---

api/v1/interface.go
scrapers/aws/cloudtrail.go

exclusions in changes from Cloudtrail were not working because the change didn't have the base scraper from which we were reading the exclusions.

fix: changes from cloudtrail

---

db/config.go
db/models/config_item.go
db/update.go
go.mod
go.sum
scrapers/cron.go

- optimize setting the parent & the config path on the first run. 
- This fixes having to run the scraper at least twice to setup the parent_id properly. 
- fixes incorrect evaluation of config path
- Bulk saving of new config items, new config changes & updates to config changes.

fix: parent & path of configs & batch saving

---

db/models/config_item.go
db/update.go

results that only contained changes should not be put into graph.
`ConsumeKubernetesWatchEvents{b8e78065-c9e4-40c8-bcf0-de3a39423092} failed to save results: failed to update db: failed to extract configs & changes from results: unable to add vertex(/ id=): vertex already exists
`

fix: addition of vertices for changes only results

---

chart/templates/deployment.yaml

So it can use the global value when being used as a subchart.

fix: chart otel labels

---

db/config.go
db/update.go
go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum
scrapers/kubernetes/kubernetes.go

merge after: https://github.com/flanksource/duty/pull/761
- changes related to the change in unique constraint in the `config_relationships` table
- set the deployment/replicaset as the parent of a pod depending on exclusion

fix: config_relationship & kubernetes pod parent

---

db/update.go
scrapers/aws/aws.go
scrapers/aws/cloudtrail.go
scrapers/cron.go

resolves: https://github.com/flanksource/config-db/issues/537
When saving changes the `config_id` was either `""` or a generated uuid of a non existing config items _(example: change from a kubernetes event for replicaset but it's excluded from scraping)_.

fix: saving changes for non existing configs

---

db/update.go
scrapers/cron.go

when forming partial graphs we'll often try to insert duplicate edges. It's safe to ignore that error.
Example: when we fetch two deployment parents after receiving two different pods in a batch of event, we try to add edges from the paths in the deployment.
```
Deploy A path: Cluster.Namespace.DA
Deploy B path: Cluster.Namespace.DB
```
`Cluster->Namespace` edge is then attempted to add twice.

fix: dont error out on duplicate edge insertion

---

api/v1/types.go
db/config.go
db/models/config_item.go
db/update.go
scrapers/cron.go
scrapers/kubernetes/events_watch.go
scrapers/kubernetes/kubernetes.go

resolves: https://github.com/flanksource/config-db/issues/559
When a pod of a job is deleted, an event isn't created. We need to delete the pod based in the watch event type.

fix: handle deletion of configs

---

scrapers/azure/azure.go

@moshloop This is the fix for https://mission-control.workload-prod-eu-01.flanksource.com/settings/config_scrapers/b302865d-b948-463d-8f0a-6fa1e95cec1c?name=Scraper
I think we might have to refactor how scrape context works with duty context

chore: use scrape ctx namespace for azure

---

scrapers/aws/aws.go
utils/json.go

Fixes: https://github.com/flanksource/config-db/issues/126

chore: convert policy doc to json

---

db/models/config_item.go
db/update.go
scrapers/kubernetes/kubernetes.go

resolves: https://github.com/flanksource/config-db/issues/585
In an incremental scraper, we don't have the namespace object. Hence, resourceIDMap would be empty for all the namespaces. 
If any namespaced object, like a Deployment, were to be scraped by the incremental scraper, we wouldn't be able to set the parent of that deployment because we don't know the id of the parent namespace.
In the workload cluster, the incremental scraper wasn't able to set the parent for a newly created cronjob so the saving of CronJob config failed. Consequently, saving of the job and also the pod would fail. This would happen until a full scrape.
**The fix**: use the Namespace config alias as the parent's external id.

fix: parent id of Namespace & Cluster in incremental k8s scraper

---

jobs/cleanup.go

resolves: https://github.com/flanksource/config-db/issues/590

feat: config_items cleanup

---

db/update.go
scrapers/aws/aws.go
scrapers/cron.go
scrapers/run.go

resolves: https://github.com/flanksource/config-db/issues/577
We use a virtual root to deal with graphs with multiple parent-less items.
Fixes:

fix: paths for availability zone & zone ID in aws scraper

---

db/config.go
scrapers/cron.go
scrapers/kubernetes/events_watch.go
scrapers/kubernetes/informers.go

The deleted objected must only be processed after added/updated objects
resolves: https://github.com/flanksource/config-db/issues/598
resolves: https://github.com/flanksource/config-db/issues/605

fix: bring back buffer for delete

---

jobs/cleanup.go

Fixes: https://github.com/flanksource/config-db/issues/638

fix: delete correct parent relationship in config item cleanup query

---

go.mod
go.sum
scrapers/kubernetes/kubernetes.go

Depends on: https://github.com/flanksource/ketall/pull/9
Fixes: https://github.com/flanksource/config-db/issues/659

chore: (k8s) return explicit error in case of insufficient access

---

db/update.go
scrapers/kubernetes/kubernetes.go

resolves: https://github.com/flanksource/config-db/issues/668

feat: Helm direct parent

---

api/v1/aws.go
db/update.go
go.mod
go.sum
scrapers/aws/aws.go
scrapers/aws/cloudtrail.go
scrapers/aws/config.go

resolves: https://github.com/flanksource/config-db/issues/665

feat(aws): new services

---

db/update.go

Having a high error count without any description does not make sense

chore: cleaner error count for orphaned

---

scrapers/aws/aws.go
scrapers/kubernetes/kubernetes.go

~~## fix source vertex not found error by namespacing all look ups to the scraper.~~
~~The source vertex not found error would occur only in cases where multiple clusters were being scraped. The lookups needed to be scoped to the given scraper.~~
~~_Example_: When forming a `Namespace default` -> `Deployment Nginx` relationship for **cluster A,** the lookup for external id `Kubernetes/Namespace//default` would return the ID of the `default namespace` from **cluster B.** This would cause failure when forming the graph as the edge couldn't be inserted since there's no source vertex in the graph.~~
~~resolves: https://github.com/flanksource/config-db/issues/703~~

feat: link kubernetes LB services to AWS ELB

---

scrapers/aws/aws.go

resolves: https://github.com/flanksource/config-db/issues/706

feat(aws): sqs, sns, ecs task scraper fixes

---

db/update.go

* for configs with no creation timestamp (example: Kubernetes cluster), we were always updating the created_at field. More so, the field was set to zero value.
* for configs that weren't deleted, we were always updating the deleted_at field to a NULL value. Now, we only set to NULL if the existing config was actually deleted before.
This fixes the accuracy of the updated rows counter.
resolves: https://github.com/flanksource/config-db/issues/707

fix: updating creation & deletion timestamps

---

api/v1/aws.go
api/v1/aws_test.go

resolves: https://github.com/flanksource/config-db/issues/715

feat: disable aws task definition scraper by default

---

api/cache.go
scrapers/aws/aws.go

We have two helm releases with the same name on the same namespace but different ids.
The deleted one is being fetched currently when setting up the parent.

fix: exclude deleted when looking up by external id

---

api/cache.go
api/context.go
scrapers/kubernetes/kubernetes.go

On the aws cluster, we had two HelmReleases under the same scraper with the same KNN & external ids. One of them is deleted & the other is active.
On temp cache init, we would fetch both the helm releases but the older (deleted) one would replace the active one in the cache.
The parent lookup for all the resources created by the helm release would then get the wrong parent id and the graph formation would fail.

fix: parent lookup

---

scrapers/aws/aws_session.go

Giving custom endpoints require signing region as well

chore: add signing region to aws endpoint resolver

---

db/models/config_change.go
db/update.go

resolves: https://github.com/flanksource/config-db/issues/827
On full scrape, it's possible that we try to save the same k8s event or cloudtrail event twice.
On external_change_id conflict, ~~we should do nothing.~~ we update all the columns. The existing code set the on conflict clause to the id column.
Here's one of the change that was causing the unique constraint error
```json
{
"id": "a1da9c2f-036e-44c3-b41a-ba5e6f7a296e",
"config_id": "0ebe0548-9f35-4227-8eee-0f33d73a7f28",
"external_change_id": "bba882cb-0817-43f8-902d-36541aab55d7",
"external_created_by": null,
"change_type": "GitOperationSucceeded",
"severity": "info",
"source": "source-controller",
"summary": "no changes since last reconcilation: observed revision 'master@sha1:0778012042fb4d523cb03179ee6e4a0d2c5a9eda'", …
```

fix: duplicate key value violates unique constraint "config_changes_config_id_external_change_id_key"

---

scrapers/aws/aws.go

when an Ec2 instance is in `Terminated` status, `GetHostname()` returns an empty string.
resolves: https://github.com/flanksource/config-db/issues/915

fix(aws scraper): handle empty name for ec2 instances

---

api/cache.go
scrapers/kubernetes/exclusions.go
scrapers/processors/json.go

My best assumption is that this is due to us adding a tag["zone"] = var, where var is an empty string, added more details about the config item here
We probably our trying to "get" items that do not exist (or are ignored) from temp cache/database, we should probably use .Find() in the `ctx.getObjectChangeExclusionAnnotations(string(event.InvolvedObject.UID))` function

chore: add better error messages for scrape errors

---

api/v1/interface.go

We have to do this check because terminated instances that get scraped do not have zones (which we get from subnet id which is empty in this case)
Should we:
a) Just handle for this case ?
b) Remove the tag eval error which says `failed to evaluate tags for result[VirtualMachine/ip-172-29-130-89.eu-west-1.compute.internal (i-07dbff1b152cd402e) relationships=400]: tag "zone" should specify either value, jsonpath or label`
c) in tags.append, skip if value is empty

chore: do not append tags if empty

---

api/cache.go
api/v1/interface.go
db/config_scraper.go
db/update.go
jobs/retention.go
scrapers/cron.go

This was causing a lot of bugs and unexpected results in catalog features
Old scrapers were replaced with new but config items' scraper id was not updated, and most of our post process jobs  use non deleted scraper_ids

fix: update scraper id for config item

---

jobs/cleanup.go
scrapers/run.go
scrapers/stale.go

If the agents somehow fail to reconcile soft deletes of stale items before the stale items are hard deleted, they remain on the upstream indefinitely.
This has happened & our azure sandbox.

feat: new job to handle stale items from agents

---

api/global.go
cmd/operator.go
cmd/run.go
cmd/server.go
controllers/scrapeconfig_controller.go
db/changes.go
db/config_scraper.go
scrapers/cron.go
scrapers/runscrapers_test.go

Scrape contexts are scrape config specific (or request specific). Doesn't make sense to have a global one and it's not even required.
An echo handler was also using the global context instead of the request context which caused a bug where the span wasn't propagated.

chore: remove global scrape context

---

cmd/operator.go
controllers/scrapeconfig_controller.go

The context the reconciler handler receives is a plain gocontext with no db in it.
Couldn't find a way to add a middleware to inject our duty context. 
So added the db as a struct field.

fix: reconciler db

---

api/v1/aws.go

Trusted advisor analyses were not running because of this

fix: aws resource exclusion logic

---

scrapers/kubernetes/informers.go

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x87369e1]
goroutine 135 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:115 +0x1e5
panic({0x908ebc0?, 0xe27ef80?})
/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/flanksource/config-db/scrapers/kubernetes.(*SharedInformerManager).getOrCreate(0xe57c080, {{{{0xad06b40, 0xc00a73d650}, {0xad3d7f0, 0xc000b2c690}, 0x9f817a0, 0x9f817a8, {0xac81ce0, 0xc00045edf0}}}, 0xc005596fa8, ...}, ...)
/app/scrapers/kubernetes/informers.go:111 …
```

fix: handle nil ptr error for empty kubeconfig

---

api/v1/kubernetes.go
scrapers/kubernetes/events_test.go
scrapers/kubernetes/events_watch.go

resolves: https://github.com/flanksource/config-db/issues/1007
mapstructure couldn't properly decode watch events into `v1.KubernetesEvent`. More specifically, the creation timestamp would get lost (it was zero value).
On the other hand, the events that came from a full scrape had the creation timestamp set.
This would cause mismatch in the change details and we would increment the count based on this logic: https://github.com/flanksource/duty/blob/main/views/030_config_changes.sql#L13

fix: kubernetes event creation timestamps

---

scrapers/kubernetes/kubernetes.go

we were getting resource not found errors when fetching resources with the dynamic client.
The issue was that the "Kind" alone wasn't specific enough to get the correct dynamic client. Example: I had two HelmChart kinds
```
helmcharts                                         helm.cattle.io/v1                        true         HelmChart
helmcharts                         hc              source.toolkit.fluxcd.io/v1              true         HelmChart
```
Changed that to create the dynamic client for <Group, Version, Kind> instead.

fix: dynamic client for ambigious Kind

---

db/update.go

get the health directly from the database as a previous result in the same batch might have already updated the previous health.
**example**: 
previous health = unhealthy
result1: changes to healthy
result2: changes to healthy (❌ this should be discarded as it's already healthy)
resolves: https://github.com/flanksource/config-db/issues/1146

fix: health changes

---

api/context.go

If we pass an object in `ctx.WithObject` it does not behave well with `ctx.GetName()` and `ctx.GetNamespace()`
Maybe we should make `.WithObject()` only take metav1.Object ?

fix: secret not found problem

---

api/v1/interface.go
db/update.go
scrapers/cron.go
scrapers/kubernetes/events_watch.go
scrapers/kubernetes/informers.go
scrapers/kubernetes/kubernetes.go

resolves: https://github.com/flanksource/config-db/issues/1168
This happens on two scenarsio
**1. Resources watched via the resource watcher are created and then deleted when config-db is down.**
In this case, when config-db is back up 
- the resource watcher will not receive the object _(if it was live, then it would have)._
- however, the event watcher will still receive all the events for that object. The configs aren't excluded _(they are missed)_ so we try to save the changes.
**2.** (bug) if an object is excluded via labels
The object gets excluded due to the label.
However, the event cannot exclude it as the event object's involved object doesn't have the label.
Adding exclusion cache doesn't help because if the event consumer runs first before it's excluded, we run into the same …

fix: config_changes_config_id_fkey

---

scrapers/kubernetes/ketall.go

We were processing the same events again and again due to having both a Watcher for events and full scrape

chore: exclude events in full scrape

---

scrapers/incremental.go
scrapers/kubernetes/informers.go
scrapers/kubernetes/informers_test.go

* use queue for deleted objects as well. Get rid of delete buffers so every updates from the shared informers go into the queue.

feat: shared informer priority queue improvements

---

scrapers/kubernetes/informers.go

Got this error, not sure why since nil objects do not go into queue
```
panic: interface conversion: interface {} is nil, not *kubernetes.QueueItem
goroutine 3048372 [running]:
github.com/flanksource/config-db/scrapers/kubernetes.pqComparator({0x0?, 0x0?}, {0x8b41ce0?, 0xc0080548c0?})
/home/yash/Work/config-db/scrapers/kubernetes/informers.go:353 +0x31d
github.com/emirpasic/gods/trees/binaryheap.(*Heap).bubbleDownIndex(0xc001563ad0, 0x0?)
/home/yash/go/pkg/mod/github.com/emirpasic/gods@v1.18.1/trees/binaryheap/binaryheap.go:133 +0xf0
github.com/emirpasic/gods/trees/binaryheap.(*Heap).bubbleDown(...)
/home/yash/go/pkg/mod/github.com/emirpasic/gods@v1.18.1/trees/binaryheap/binaryheap.go:121
github.com/emirpasic/gods/trees/binaryheap.(*Heap).Pop(0xc001563ad0?) …
```

chore: handle nil for pq

---

scrapers/kubernetes/kubernetes.go

resolves: https://github.com/flanksource/config-db/issues/1230
resolves: https://github.com/flanksource/config-db/issues/1223

fix: service & ingress relationships

---

db/update.go

when a new config was inserted, we never updated the temp cache. As a result, once the config is set as not found - any subsequent Get() calls to that config returns not found and we treat the same config as a new one.
resolves: https://github.com/flanksource/config-db/issues/1242

fix: scraper_added metrics

---

scrapers/kubernetes/informers.go

* the lastUpdated time was calculated against the informer's registration time instead of the current time.
Here are some logs where time.Now() was just a few ms ahead.
```
20:57:44.131 WRN (watch.homelab) Pod/default/ittools-6cbf6bcbd9-88h5j has last updated time -131.105383ms into the future. now=2024-12-09 15:12:44.131105383 +0000 UTC, lastupdatedTime=2024-12-09 15:12:44 +0000 UTC
20:57:44.139 WRN (watch.homelab) Pod/default/ittools-6cbf6bcbd9-74n7m has last updated time -139.018936ms into the future. now=2024-12-09 15:12:44.139018936 +0000 UTC, lastupdatedTime=2024-12-09 15:12:44 +0000 UTC
20:57:44.15 WRN (watch.homelab) Pod/default/ittools-6cbf6bcbd9-88h5j has last updated time -149.744873ms into the future. now=2024-12-09 15:12:44.149744873 +0000 UTC, lastupdatedTime=2024-12-09 …
```

fix: metric lag calculation for update events

---

db/update.go

resolves: https://github.com/flanksource/config-db/issues/1249
This happened after a full scrape when we run `InitTempCache` which caches the entire configs of the scraper to `scraperTempCache`.
During scaling up (from replica 1 to 4)
- first event:
all replicas aren't ready so we save `health = warning` to the db. But this was never updated in the cache.
- second event:
all replicas are ready so we try to update the config `health = healthy`.
The comparison is done against the stale cache which also has `health = healthy`.
config-db sees no change in health and doesn't update the health in db leaving a fully ready deployment in a warning state.

fix: sync cache on config updates

---

scrapers/aws/aws.go

Fixes: https://github.com/flanksource/config-db/issues/1198

chore: remove zone relationship

---

api/cache.go
db/config.go
go.mod
go.sum
scrapers/run_test.go

huge spike in config query call in the last 2 weeks

feat: metrics on temp cache

---

scrapers/incremental.go

resolves: https://github.com/flanksource/config-db/issues/441

feat: kubernetes aws connection

---

Makefile
chart/README.md
chart/values.schema.json

additionalProperties were set to `false` here: https://github.com/flanksource/config-db/pull/1397
Upgrades were failing
```
Helm upgrade failed for release mission-control/mission-control with chart mission-control@0.1.237-beta.1: values don't meet the specifications of the schema(s) in the following chart(s):
config-db:
- global: Additional property logLevel is not allowed
- global: Additional property ui is not allowed
- global: Additional property api is not allowed
- global.db.connectionPooler: Additional property extraContainers is not allowed
- global.db.connectionPooler: Additional property image is not allowed
- global.db.connectionPooler: Additional property serviceAccount is not allowed
- serviceAccount.annotations: Additional property eks.amazonaws.com/role-arn is not allowed …
```

fix(chart): additional properties

---

db/config.go

FieldSelector is basically a property selector now.
Configs were not being linked properly.
Example: GitRepository was not linked to Kustomization

fix: Kubernetes relationship

---

scrapers/aws/aws.go

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x990a660]
goroutine 12906 [running]:
github.com/flanksource/config-db/scrapers/aws.Scraper.eksClusters({}, _, {{{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}, ...}, ...)
/app/scrapers/aws/aws.go:761 +0xce0
github.com/flanksource/config-db/scrapers/aws.Scraper.Scrape({}, {{{{0xc72c570, 0xc00d5485a0}, {0xc7769d0, 0xc00d548480}, 0xbc50718, 0xbc50720, {0xc6983f0, 0xc0009e8540}}}, 0xc001110d20, ...})
/app/scrapers/aws/aws.go:1846 +0xba8
github.com/flanksource/config-db/scrapers.Run({{{{0xc72c570, 0xc00d5485a0}, {0xc7769d0, 0xc00d548480}, 0xbc50718, 0xbc50720, {0xc6983f0, 0xc0009e8540}}}, 0xc001110d20, 0x0, ...})
/app/scrapers/run.go:112 +0x4bd …
```

fix: handle empty vpc id for eks
